import { account, databases } from "@/lib/appwrite.config";
import * as sdk from "node-appwrite";

const DATABASE_ID = '6720cc9c000049efcd3c';
const PATIENT_COLLECTION_ID = '6720ccbd0028468dee7e';

export async function loginUser({
  email,
  password,
}: {
  email: string;
  password: string;
}) {
  try {
    // Use Appwrite's createEmailSession API
    const session = await account.createEmailPasswordSession(
      email,
      password
    );

    // Return the session object for successful login
    return { success: true, session };
  } catch (error: any) {
    console.error("Login error:", error);
    throw new Error(error.message || "Login failed. Please try again.");
  }
}


// Function to register a user
export async function registerUser({
  email,
  password,
  fullName,
  age,
  dateOfBirth,
  contactNo,
  sex,
  items,
}: {
  email: string;
  password: string;
  fullName: string;
  age: number;
  dateOfBirth: string;
  contactNo: string;
  sex: string;
  items: string[];
}) {
  try {
    // Create user in Appwrite authentication system
    const user = await account.create(
      "unique()", // unique ID generated by Appwrite
      email,
      password,
      fullName
    );

    // Create document in Appwrite database with additional user information
    await databases.createDocument(
      DATABASE_ID,
      PATIENT_COLLECTION_ID,
      "unique()",
      {
        fullName,
        email,
        age,
        birthday: dateOfBirth,
        number: contactNo, // No conversion needed; it's already a string
        medicalConcerns: items,
        sex,
        password,
      },
      [
        sdk.Permission.read("users"),
        sdk.Permission.update("users"),
      ]
    );    

    return { success: true, user };
  } catch (error) {
    console.error("Registration error:", error);
    throw new Error("Registration failed. Please try again.");
  }
}
